language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t plato28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plato28/react-test npm run test

after_success:
  - docker build -t plato28/multi-client ./client
  - docker build -t plato28/multi-nginx ./nginx
  - docker build -t plato28/multi-server ./server
  - docker build -t plato28/multi-worker ./worker
