language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t plato28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plato28/react-test npm run test

after_success:
  - docker build -t plato28/multi-client ./client
  - docker build -t plato28/multi-nginx ./nginx
  - docker build -t plato28/multi-server ./server
  - docker build -t plato28/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push plato28/multi-client
  - docker push plato28/multi-nginx
  - docker push plato28/multi-server
  - docker push plato28/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "multi-fib"
  env: "Multifib-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-822637900730"
  bucket_path: "multi-fib"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
